version: '3.1'

services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DATABASE_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DATABASE_PASS}"
      MONGO_INITDB_DATABASE: "${DATABASE_NAME}"
      
    ports:
      - 27017:27017